
export const ACTION_TYPES = {
//----------------------------------------------------------------Admin
    ADMIN_LOGIN_REQUEST: 'ADMIN_LOGIN_REQUEST',
    ADMIN_LOGIN_SUCCESS: "ADMIN_LOGIN_SUCCESS",
    ADMIN_LOGIN_FAILED: "ADMIN_LOGIN_FAILED",

    ADMIN_LOGOUT_REQUEST: 'ADMIN_LOGOUT_REQUEST',
    ADMIN_LOGOUT_SUCCESS: "ADMIN_LOGOUT_SUCCESS",
    ADMIN_LOGOUT_FAILED: "ADMIN_LOGOUT_FAILED",

//----------------------------------------------------------------ARBOR
    ADD_ARBOR_REQUEST: 'ADD_ARBOR_REQUEST',
    ADD_ARBOR_SUCCESS: 'ADD_ARBOR_SUCCESS',
    ADD_ARBOR_FAILED: 'ADD_ARBOR_FAILED',

    FETCH_ARBOR_REQUEST: 'FETCH_ARBOR_REQUEST',
    FETCH_ARBOR_SUCCESS: 'FETCH_ARBOR_SUCCESS',
    FETCH_ARBOR_FAILED: 'FETCH_ARBOR_FAILED',

    EDIT_ARBOR_REQUEST: 'EDIT_ARBOR_REQUEST',
    EDIT_ARBOR_SUCCESS: 'EDIT_ARBOR_SUCCESS',
    EDIT_ARBOR_FAILED: 'EDIT_ARBOR_FAILED',

    SET_ARBOR_REQUEST: 'SET_ARBOR_REQUEST',
    SET_ARBOR_SUCCESS: 'SET_ARBOR_SUCCESS',
    SET_ARBOR_FAILED: 'SET_ARBOR_FAILED',

    DELETE_ARBOR_REQUEST: 'DELETE_ARBOR_REQUEST',
    DELETE_ARBOR_SUCCESS: 'DELETE_ARBOR_SUCCESS',
    DELETE_ARBOR_FAILED: 'DELETE_ARBOR_FAILED',


    //----------------------------------------------------------------HEALTHRATE
    ADD_HEALTHRATE_REQUEST: 'ADD_HEALTHRATE_REQUEST',
    ADD_HEALTHRATE_SUCCESS: 'ADD_HEALTHRATE_SUCCESS',
    ADD_HEALTHRATE_FAILED: 'ADD_HEALTHRATE_FAILED',

    FETCH_HEALTHRATE_REQUEST: 'FETCH_HEALTHRATE_REQUEST',
    FETCH_HEALTHRATE_SUCCESS: 'FETCH_HEALTHRATE_SUCCESS',
    FETCH_HEALTHRATE_FAILED: 'FETCH_HEALTHRATE_FAILED',

    EDIT_HEALTHRATE_REQUEST: 'EDIT_HEALTHRATE_REQUEST',
    EDIT_HEALTHRATE_SUCCESS: 'EDIT_HEALTHRATE_SUCCESS',
    EDIT_HEALTHRATE_FAILED: 'EDIT_HEALTHRATE_FAILED',

    SET_HEALTHRATE_REQUEST: 'SET_HEALTHRATE_REQUEST',
    SET_HEALTHRATE_SUCCESS: 'SET_HEALTHRATE_SUCCESS',
    SET_HEALTHRATE_FAILED: 'SET_HEALTHRATE_FAILED',

    DELETE_HEALTHRATE_REQUEST: 'DELETE_HEALTHRATE_REQUEST',
    DELETE_HEALTHRATE_SUCCESS: 'DELETE_HEALTHRATE_SUCCESS',
    DELETE_HEALTHRATE_FAILED: 'DELETE_HEALTHRATE_FAILED',


    //----------------------------------------------------------------RECOMMENDATION
    ADD_RECOMMENDATION_REQUEST: 'ADD_RECOMMENDATION_REQUEST',
    ADD_RECOMMENDATION_SUCCESS: 'ADD_RECOMMENDATION_SUCCESS',
    ADD_RECOMMENDATION_FAILED: 'ADD_RECOMMENDATION_FAILED',

    FETCH_RECOMMENDATION_REQUEST: 'FETCH_RECOMMENDATION_REQUEST',
    FETCH_RECOMMENDATION_SUCCESS: 'FETCH_RECOMMENDATION_SUCCESS',
    FETCH_RECOMMENDATION_FAILED: 'FETCH_RECOMMENDATION_FAILED',

    EDIT_RECOMMENDATION_REQUEST: 'EDIT_RECOMMENDATION_REQUEST',
    EDIT_RECOMMENDATION_SUCCESS: 'EDIT_RECOMMENDATION_SUCCESS',
    EDIT_RECOMMENDATION_FAILED: 'EDIT_RECOMMENDATION_FAILED',

    SET_RECOMMENDATION_REQUEST: 'SET_RECOMMENDATION_REQUEST',
    SET_RECOMMENDATION_SUCCESS: 'SET_RECOMMENDATION_SUCCESS',
    SET_RECOMMENDATION_FAILED: 'SET_RECOMMENDATION_FAILED',

    DELETE_RECOMMENDATION_REQUEST: 'DELETE_RECOMMENDATION_REQUEST',
    DELETE_RECOMMENDATION_SUCCESS: 'DELETE_RECOMMENDATION_SUCCESS',
    DELETE_RECOMMENDATION_FAILED: 'DELETE_RECOMMENDATION_FAILED',


    //----------------------------------------------------------------SPECIES
    ADD_SPECIES_REQUEST: 'ADD_SPECIES_REQUEST',
    ADD_SPECIES_SUCCESS: 'ADD_SPECIES_SUCCESS',
    ADD_SPECIES_FAILED: 'ADD_SPECIES_FAILED',

    FETCH_SPECIES_REQUEST: 'FETCH_SPECIES_REQUEST',
    FETCH_SPECIES_SUCCESS: 'FETCH_SPECIES_SUCCESS',
    FETCH_SPECIES_FAILED: 'FETCH_SPECIES_FAILED',

    EDIT_SPECIES_REQUEST: 'EDIT_SPECIES_REQUEST',
    EDIT_SPECIES_SUCCESS: 'EDIT_SPECIES_SUCCESS',
    EDIT_SPECIES_FAILED: 'EDIT_SPECIES_FAILED',

    SET_SPECIES_REQUEST: 'SET_SPECIES_REQUEST',
    SET_SPECIES_SUCCESS: 'SET_SPECIES_SUCCESS',
    SET_SPECIES_FAILED: 'SET_SPECIES_FAILED',

    DELETE_SPECIES_REQUEST: 'DELETE_SPECIES_REQUEST',
    DELETE_SPECIES_SUCCESS: 'DELETE_SPECIES_SUCCESS',
    DELETE_SPECIES_FAILED: 'DELETE_SPECIES_FAILED',

    //-----------------------------------------------------------------------Other Species
    
    FETCH_OTHER_SPECIES_REQUEST: 'FETCH_OTHER_SPECIES_REQUEST',
    FETCH_OTHER_SPECIES_SUCCESS: 'FETCH_OTHER_SPECIES_SUCCESS',
    FETCH_OTHER_SPECIES_FAILED: 'FETCH_OTHER_SPECIES_FAILED',
    
    DELETE_OTHER_SPECIES_REQUEST: 'DELETE_OTHER_SPECIES_REQUEST',
    DELETE_OTHER_SPECIES_SUCCESS: 'DELETE_OTHER_SPECIES_SUCCESS',
    DELETE_OTHER_SPECIES_FAILED: 'DELETE_OTHER_SPECIES_FAILED',

    //----------------------------------------------------------------Company
    ADD_COMPANY_REQUEST: 'ADD_COMPANY_REQUEST',
    ADD_COMPANY_SUCCESS: 'ADD_COMPANY_SUCCESS',
    ADD_COMPANY_FAILED: 'ADD_COMPANY_FAILED',

    FETCH_COMPANY_REQUEST: 'FETCH_COMPANY_REQUEST',
    FETCH_COMPANY_SUCCESS: 'FETCH_COMPANY_SUCCESS',
    FETCH_COMPANY_FAILED: 'FETCH_COMPANY_FAILED',

    EDIT_COMPANY_REQUEST: 'EDIT_COMPANY_REQUEST',
    EDIT_COMPANY_SUCCESS: 'EDIT_COMPANY_SUCCESS',
    EDIT_COMPANY_FAILED: 'EDIT_COMPANY_FAILED',

    SET_COMPANY_REQUEST: 'SET_COMPANY_REQUEST',
    SET_COMPANY_SUCCESS: 'SET_COMPANY_SUCCESS',
    SET_COMPANY_FAILED: 'SET_COMPANY_FAILED',

    DELETE_COMPANY_REQUEST: 'DELETE_COMPANY_REQUEST',
    DELETE_COMPANY_SUCCESS: 'DELETE_COMPANY_SUCCESS',
    DELETE_COMPANY_FAILED: 'DELETE_COMPANY_FAILED',

    FETCH_COMPANY_ARBORS_REQUEST: 'FETCH_COMPANY_ARBORS_REQUEST',
    FETCH_COMPANY_ARBORS_SUCCESS: 'FETCH_COMPANY_ARBORS_SUCCESS',
    FETCH_COMPANY_ARBORS_FAILED:  'FETCH_COMPANY_ARBORS_FAILED',
}